services:
  app:
    container_name: conexaoSocias
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3009:3009"
    environment:
      - NODE_ENV=production
      - PORT=3009
    networks:
      - rede_global_nginx

networks:
  rede_global_nginx:
    external: true
